CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    body       TEXT                                    NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    description  TEXT                                    NOT NULL,
    body         TEXT                                    NOT NULL,
    reading_time INTEGER DEFAULT 1                       NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    author_id    BIGINT,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE posts_tags
(
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_posts_tags PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    slug VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tags
    ADD CONSTRAINT uc_tags_slug UNIQUE (slug);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE posts_tags
    ADD CONSTRAINT fk_postag_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE posts_tags
    ADD CONSTRAINT fk_postag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);